# Generated by Django 3.2.7 on 2021-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_type',
            field=models.CharField(choices=[('C', 'Creator'), ('A', 'Approver')], default='C', max_length=32),
        ),
    ]
