version: '3.7'

services: 
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app/backend/
        command: >
            sh -c "python manage.py migrate --no-input && 
            python manage.py collectstatic --no-input && 
            gunicorn core.wsgi --bind 0.0.0.0:8000 --workers 2 --threads 4"
        env_file:
            - ./docker/docker.app.env
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./docker/docker.db.env
        expose:
            - 5432
volumes:
    postgres_data: