# Generated by Django 3.2.7 on 2021-10-04 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AproverNotification',
            fields=[
                ('notifcation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excelLink', models.URLField()),
                ('emailSend', models.BooleanField(default=False)),
                ('workDone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprover_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
