# Generated by Django 3.2.7 on 2021-10-04 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovernotification',
            name='linkCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aprovernotification',
            name='excelLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aprovernotification',
            name='notifcation_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
