# Generated by Django 3.2.7 on 2021-10-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20211005_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvernotification',
            name='linkCreated',
        ),
    ]
