# Generated by Django 3.2.7 on 2021-10-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211003_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='choice',
            field=models.CharField(choices=[('Spirit', 'Spirit'), ('Profession', 'Profession'), ('Purpose', 'Purpose'), ('Reward', 'Reward')], max_length=10, null=True),
        ),
    ]
