# Generated by Django 3.2.7 on 2021-10-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emotion_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelings',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feelings_emotion', to='app.emotion'),
        ),
    ]
