# Generated by Django 3.2.7 on 2021-10-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_sitution_lifevector_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed',
            name='excelLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openleading',
            name='excelLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qpen',
            name='excelLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
