# Generated by Django 3.2.7 on 2021-10-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20211004_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed',
            name='approverEmail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openleading',
            name='approverEmail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openleading_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qpen',
            name='approverEmail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
