# Generated by Django 3.2.7 on 2021-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211007_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummylist',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='dummylist',
            name='question',
            field=models.CharField(choices=[('Who', 'Who'), ('Which', 'Which'), ('Where', 'Where'), ('When', 'When'), ('What', 'What')], default='Who', max_length=5),
        ),
        migrations.RemoveField(
            model_name='dummylist',
            name='category',
        ),
        migrations.AddField(
            model_name='dummylist',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='dummylist_c', to='app.Category'),
        ),
        migrations.RemoveField(
            model_name='dummylist',
            name='decade',
        ),
        migrations.AddField(
            model_name='dummylist',
            name='decade',
            field=models.ManyToManyField(blank=True, null=True, related_name='dummylist_decade', to='app.Decade'),
        ),
        migrations.RemoveField(
            model_name='dummylist',
            name='genre',
        ),
        migrations.AddField(
            model_name='dummylist',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='dummylist_genre', to='app.Genre'),
        ),
    ]
