# Generated by Django 3.2.7 on 2021-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211007_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummylist',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='dummylist_c', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='dummylist',
            name='decade',
            field=models.ManyToManyField(blank=True, related_name='dummylist_decade', to='app.Decade'),
        ),
        migrations.AlterField(
            model_name='dummylist',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='dummylist_genre', to='app.Genre'),
        ),
    ]
