# Generated by Django 3.2.7 on 2021-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeForDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('Who', 'Who'), ('Which', 'Which'), ('Where', 'Where'), ('When', 'When'), ('What', 'What')], default='Who', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='dummylist',
            name='question',
        ),
        migrations.AddField(
            model_name='dummylist',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='dummylist_question', to='app.QuestionTypeForDummy'),
        ),
    ]
