# Generated by Django 3.2.7 on 2021-10-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211007_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='selection',
            field=models.CharField(max_length=100),
        ),
    ]
