# Generated by Django 3.2.7 on 2021-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_dummy_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTypeForDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(choices=[('best', 'best'), ('worst', 'worst'), ('more intresting', 'more intresting')], default='best', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dummylist',
            name='word',
            field=models.ManyToManyField(blank=True, related_name='dummylist_word', to='app.WordTypeForDummy'),
        ),
    ]
