# Generated by Django 3.2.7 on 2021-10-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211008_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordtypefordummy',
            old_name='word',
            new_name='answer',
        ),
    ]
