# Generated by Django 3.2.7 on 2021-10-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_word_wordtypefordummy_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Life Vector', 'Life Vector'), ('Learning Method', 'Learning Method'), ('Intelligent Dummy', 'Intelligent Dummy'), ('Dummy', 'Dummy')], max_length=20)),
                ('sheetID', models.CharField(max_length=200)),
            ],
        ),
    ]
