# Generated by Django 3.2.7 on 2021-10-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211011_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyAnswersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_c', to='app.category')),
                ('decade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_decade', to='app.decade')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_genre', to='app.genre')),
                ('word', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_word', to='app.wordtypefordummy')),
            ],
        ),
    ]
