# Generated by Django 3.2.7 on 2021-10-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_dummyanswerslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyanswerslist',
            name='category',
        ),
        migrations.AddField(
            model_name='dummyanswerslist',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_c', to='app.subcategory'),
        ),
        migrations.AlterField(
            model_name='dummyanswerslist',
            name='decade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_decade', to='app.decade'),
        ),
        migrations.AlterField(
            model_name='dummyanswerslist',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_genre', to='app.genre'),
        ),
        migrations.AlterField(
            model_name='dummyanswerslist',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummyanslist_word', to='app.wordtypefordummy'),
        ),
    ]
