# Generated by Django 3.2.7 on 2021-10-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211011_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyanswerslist',
            name='word',
        ),
    ]
