# Generated by Django 3.2.7 on 2021-10-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_dummyanswerslist_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closed',
            name='excelLink',
        ),
        migrations.RemoveField(
            model_name='openleading',
            name='excelLink',
        ),
    ]
