# Generated by Django 3.2.7 on 2021-10-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20211011_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closed',
            old_name='approverEmail',
            new_name='approver',
        ),
        migrations.RenameField(
            model_name='openleading',
            old_name='approverEmail',
            new_name='approver',
        ),
    ]
